GET http://localhost:5000/

###
GET http://localhost:5000/projects/61eac957c59cf41562d1fdeb


###
POST https://siddhesh-api.herokuapp.com/
Content-Type: application/json
{
    "name": "mern",
    "description":"this is awsome project"
}

###
DELETE https://siddhesh-api.herokuapp.com/61f91d27e06914f9e481c5e1/siddhesh

###
PATCH  https://siddhesh-api.herokuapp.com/61f91d27e06914f9e481c5e1/siddhesh
Content-Type: application/json

{
    "name":"Amazon clone"
}