GET http://localhost:5000/

###
GET http://localhost:5000/projects/61eac957c59cf41562d1fdeb


###
POST https://siddhesh-api.herokuapp.com/
Content-Type: application/json
{
    "name": "mern",
    "description":"this is awsome project"
}

###
DELETE http://localhost:5000/61f91d27e06914f9e481c5e1/siddhesh

###
PATCH  http://localhost:5000/61f919f59964e9e99e2a66d4
Content-Type: application/json

{
    "name":"Amazon clone"
}